name: Node.js application

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [
          10,
          12,
          14,
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install system dependencies
        run: |
          sudo apt -qq update
          sudo apt install -y libudev-dev
          git clone -b moziot --single-branch --depth=1 https://github.com/mozilla-iot/open-zwave
          make -C open-zwave
          sudo make -C open-zwave install
      - name: Install node dependencies
        run: |
          npm install
      - name: Lint with eslint
        run: |
          npm run lint
      - name: Run unit tests
        run: |
          npm run jest
